# Generated by Django 4.2.9 on 2025-09-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("official_name", models.CharField(max_length=255)),
                ("subtype", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "accounts",
                "managed": False,
            },
        ),
    ]
